version: 0.2
phases:
  install: 
    commands: 
      - echo installing python libraries
      - pip install -r requirements.txt -t lib
      - echo upgrading aws-cli
      - pip install --upgrade awscli
  pre_build: 
    commands: 
      - python -V
      - export PYTHONPATH=$PYTHONPATH:./lib
      - export HOME_DIR=`pwd`
  build: 
    commands: 
      - echo Build started on `date`
      - echo Testing the Python code...
      - python CFexampletests.py
 post_build: 
    commands:
      - if [ $CODEBUILD_BUILD_SUCCEEDING = 1 ]; then echo Build completed on `date`;  else echo Build failed ignoring deployment; fi 
artifacts: 
  files: 
    - requirements.txt
    - cf*.json
    - CFexample.py      
